# Generated by design-to-code Component 2. Pattern: monolith
# Every resource below traces back to something detected in the source
# codebase -- no invented services, ports, or dependencies.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "vpc_id" {
  description = "VPC to deploy ECS services into"
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet IDs for ECS tasks"
  type        = list(string)
}

variable "DB_HOST" {
  description = "Environment variable required by the application"
  type        = string
}

variable "DB_PORT" {
  description = "Environment variable required by the application"
  type        = string
}

variable "DB_USER" {
  description = "Environment variable required by the application"
  type        = string
}


resource "aws_ecs_cluster" "main" {
  name = "design-to-code-cluster"
}

resource "aws_security_group" "app" {
  name        = "app-sg"
  description = "Traffic for service app"
  vpc_id      = var.vpc_id
  
  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"] # internal only
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_ecs_task_definition" "app" {
  family                   = "app"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {
      name  = "app"
      image = "REPLACE_WITH_ECR_IMAGE_URI_FOR_app"
      portMappings = [
        { containerPort = 8080, protocol = "tcp" }
      ]
      environment = [
        { name = "DB_HOST", value = var.DB_HOST },
        { name = "DB_PORT", value = var.DB_PORT },
        { name = "DB_USER", value = var.DB_USER },
        
      ]
      secrets = [
        
      ]
    }
  ])
}

resource "aws_ecs_service" "app" {
  name            = "app"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.app.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = var.private_subnet_ids
    security_groups = [aws_security_group.app.id]
  }
  
}


resource "aws_db_instance" "app_db" {
  identifier          = "app-db"
  engine              = "postgres"
  instance_class      = "db.t3.micro"
  allocated_storage   = 20
  username            = "app_user"
  password            = var.app_db_password
  skip_final_snapshot = true
  publicly_accessible = false
  # Provisioned for service: app
}

variable "app_db_password" {
  description = "Master password for app-db"
  type        = string
  sensitive   = true
}


