# Generated by design-to-code Component 2. Pattern: event-driven
# Every resource below traces back to something detected in the source
# codebase -- no invented services, ports, or dependencies.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "vpc_id" {
  description = "VPC to deploy ECS services into"
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet IDs for ECS tasks"
  type        = list(string)
}

variable "BROKER_URL" {
  description = "Environment variable required by the application"
  type        = string
}


resource "aws_ecs_cluster" "main" {
  name = "design-to-code-cluster"
}

resource "aws_security_group" "consumer" {
  name        = "consumer-sg"
  description = "Traffic for service consumer"
  vpc_id      = var.vpc_id
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_ecs_task_definition" "consumer" {
  family                   = "consumer"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {
      name  = "consumer"
      image = "REPLACE_WITH_ECR_IMAGE_URI_FOR_consumer"
      portMappings = [
        
      ]
      environment = [
        { name = "BROKER_URL", value = var.BROKER_URL },
        
      ]
      secrets = [
        
      ]
    }
  ])
}

resource "aws_ecs_service" "consumer" {
  name            = "consumer"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.consumer.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = var.private_subnet_ids
    security_groups = [aws_security_group.consumer.id]
  }
  
  # Depends on queue topic(s): orders.created (consume) 
  
}

resource "aws_security_group" "producer" {
  name        = "producer-sg"
  description = "Traffic for service producer"
  vpc_id      = var.vpc_id
  
  ingress {
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"] # internal only
  }
  
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_ecs_task_definition" "producer" {
  family                   = "producer"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {
      name  = "producer"
      image = "REPLACE_WITH_ECR_IMAGE_URI_FOR_producer"
      portMappings = [
        { containerPort = 8080, protocol = "tcp" }
      ]
      environment = [
        { name = "BROKER_URL", value = var.BROKER_URL },
        
      ]
      secrets = [
        
      ]
    }
  ])
}

resource "aws_ecs_service" "producer" {
  name            = "producer"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.producer.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = var.private_subnet_ids
    security_groups = [aws_security_group.producer.id]
  }
  
  # Depends on queue topic(s): orders.created (publish) 
  
}



resource "aws_sqs_queue" "orders_created" {
  name = "orders.created"
}

