package generator

import (
	"strings"
	"text/template"

	"github.com/Kartik-r/design-to-code/pkg/types"
)

// GenerateKubernetes produces multi-document Kubernetes YAML for the given
// schema, entirely deterministically -- no LLM, no network call.
func GenerateKubernetes(schema *types.ArchitectureSchema) (string, error) {
	view := buildView(schema)

	var sb strings.Builder
	if err := kubernetesTemplate.Execute(&sb, view); err != nil {
		return "", err
	}
	return sb.String(), nil
}

var kubernetesTemplate = template.Must(template.New("kubernetes").Parse(`# Generated by design-to-code Component 2. Pattern: {{.Pattern}}
{{range .Services}}
{{if .ConfigVars}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.SanitizedName}}-config
data:
  {{range .ConfigVars}}{{.}}: "REPLACE_ME"
  {{end}}
---
{{end}}
{{if .SecretVars}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.SanitizedName}}-secret
type: Opaque
stringData:
  {{range .SecretVars}}{{.}}: "REPLACE_ME"
  {{end}}
---
{{end}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.SanitizedName}}
  labels:
    app: {{.SanitizedName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.SanitizedName}}
  template:
    metadata:
      labels:
        app: {{.SanitizedName}}
    spec:
      containers:
        - name: {{.SanitizedName}}
          image: REPLACE_WITH_IMAGE_FOR_{{.SanitizedName}}
          {{if .HasPort}}ports:
            - containerPort: {{.PortNum}}
          {{end}}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          {{if or .ConfigVars .SecretVars}}envFrom:
            {{if .ConfigVars}}- configMapRef:
                name: {{.SanitizedName}}-config
            {{end}}{{if .SecretVars}}- secretRef:
                name: {{.SanitizedName}}-secret
            {{end}}{{end}}
{{if .QueueDeps}}      # Depends on external queue topic(s), not managed here (see Terraform):
      {{range .QueueDeps}}#   - {{.Target}} ({{.Detail}})
      {{end}}{{end}}
---
{{if .HasPort}}
apiVersion: v1
kind: Service
metadata:
  name: {{.SanitizedName}}
spec:
  selector:
    app: {{.SanitizedName}}
  ports:
    - port: {{.PortNum}}
      targetPort: {{.PortNum}}
  type: ClusterIP
---
{{end}}
{{if .IsEntrypoint}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.SanitizedName}}-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.SanitizedName}}
                port:
                  number: {{.PortNum}}
---
{{end}}
{{end}}
`))