package generator

import (
	"strings"
	"text/template"

	"github.com/Kartik-r/design-to-code/pkg/types"
)

// GenerateTerraform produces Terraform HCL for the given schema, entirely
// deterministically -- no LLM, no network call. Every resource in the
// output traces directly back to something present in the schema; nothing
// is invented.
func GenerateTerraform(schema *types.ArchitectureSchema) (string, error) {
	view := buildView(schema)

	var sb strings.Builder
	if err := terraformTemplate.Execute(&sb, view); err != nil {
		return "", err
	}
	return sb.String(), nil
}

var terraformTemplate = template.Must(template.New("terraform").Parse(`# Generated by design-to-code Component 2. Pattern: {{.Pattern}}
# Every resource below traces back to something detected in the source
# codebase -- no invented services, ports, or dependencies.

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

variable "aws_region" {
  description = "AWS region to deploy into"
  type        = string
  default     = "us-east-1"
}

variable "vpc_id" {
  description = "VPC to deploy ECS services into"
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnet IDs for ECS tasks"
  type        = list(string)
}
{{range .ConfigVarsFlat}}
variable "{{.}}" {
  description = "Environment variable required by the application"
  type        = string
}
{{end}}
{{range .SecretVarsFlat}}
variable "{{.}}" {
  description = "Sensitive environment variable required by the application"
  type        = string
  sensitive   = true
}
{{end}}
resource "aws_ecs_cluster" "main" {
  name = "design-to-code-cluster"
}
{{range .Services}}
resource "aws_security_group" "{{.TFIdent}}" {
  name        = "{{.SanitizedName}}-sg"
  description = "Traffic for service {{.Name}}"
  vpc_id      = var.vpc_id
  {{if .HasPort}}
  ingress {
    from_port   = {{.PortNum}}
    to_port     = {{.PortNum}}
    protocol    = "tcp"
    cidr_blocks = ["10.0.0.0/8"] # internal only
  }
  {{end}}
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

resource "aws_ecs_task_definition" "{{.TFIdent}}" {
  family                   = "{{.SanitizedName}}"
  requires_compatibilities = ["FARGATE"]
  network_mode             = "awsvpc"
  cpu                      = "256"
  memory                   = "512"

  container_definitions = jsonencode([
    {
      name  = "{{.SanitizedName}}"
      image = "REPLACE_WITH_ECR_IMAGE_URI_FOR_{{.SanitizedName}}"
      portMappings = [
        {{if .HasPort}}{ containerPort = {{.PortNum}}, protocol = "tcp" }{{end}}
      ]
      environment = [
        {{range .ConfigVars}}{ name = "{{.}}", value = var.{{.}} },
        {{end}}
      ]
      secrets = [
        {{range .SecretVars}}{ name = "{{.}}", valueFrom = var.{{.}} },
        {{end}}
      ]
    }
  ])
}

resource "aws_ecs_service" "{{.TFIdent}}" {
  name            = "{{.SanitizedName}}"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.{{.TFIdent}}.arn
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = var.private_subnet_ids
    security_groups = [aws_security_group.{{.TFIdent}}.id]
  }
  {{if .QueueDeps}}
  # Depends on queue topic(s): {{range .QueueDeps}}{{.Target}} ({{.Detail}}) {{end}}
  {{end}}
}
{{end}}
{{range .DBs}}
resource "aws_db_instance" "{{.TFIdent}}" {
  identifier          = "{{.ResourceName}}"
  engine              = "{{.Engine}}"
  instance_class      = "db.t3.micro"
  allocated_storage   = 20
  username            = "app_user"
  password            = var.{{.TFIdent}}_password
  skip_final_snapshot = true
  publicly_accessible = false
  # Provisioned for service: {{.ServiceName}}
}

variable "{{.TFIdent}}_password" {
  description = "Master password for {{.ResourceName}}"
  type        = string
  sensitive   = true
}
{{end}}
{{range .Queues}}
resource "aws_sqs_queue" "{{.TFIdent}}" {
  name = "{{.Topic}}"
}
{{end}}
`))